version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: bot_postgres
    restart:  unless-stopped
    env_file:
      - ./.env
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pg_data: