"""Added number

Revision ID: 5c85396a1024
Revises: 93567534d13a
Create Date: 2025-03-28 18:26:43.547293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c85396a1024'
down_revision: Union[str, None] = '93567534d13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('gift_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts', 'gift_number')
    # ### end Alembic commands ###
