"""upd gift model

Revision ID: 8a2e83a7a407
Revises: 5c85396a1024
Create Date: 2025-04-05 23:29:02.599126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2e83a7a407'
down_revision: Union[str, None] = '5c85396a1024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('gifts', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('gifts', sa.Column('model', sa.String(), nullable=False))
    op.add_column('gifts', sa.Column('background', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('symbol', sa.String(), nullable=True))
    op.add_column('gifts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('gifts', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('gifts', 'gift_pattern')
    op.drop_column('gifts', 'gift_name')
    op.drop_column('gifts', 'gift_model')
    op.drop_column('gifts', 'gift_number')
    op.drop_column('gifts', 'gift_color')
    op.drop_column('gifts', 'gift_background')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('gift_background', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gifts', sa.Column('gift_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gifts', sa.Column('gift_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gifts', sa.Column('gift_model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('gifts', sa.Column('gift_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('gifts', sa.Column('gift_pattern', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gifts', 'url')
    op.drop_column('gifts', 'updated_at')
    op.drop_column('gifts', 'symbol')
    op.drop_column('gifts', 'background')
    op.drop_column('gifts', 'model')
    op.drop_column('gifts', 'number')
    op.drop_column('gifts', 'name')
    op.drop_column('gifts', 'owner')
    # ### end Alembic commands ###
